link_handler("links \"%u\"", text=True)
image_handler("feh -ZF \"%u\"", fetch=True)
link_handler("evince \"%u\"", fetch=True, ext="pdf")

add("http://aiddata.org/blog/rss.xml")
add("http://www.washingtonpost.com/rss/homepage", tags=["Washington Post"])
add("http://aljazeera.tumblr.com/rss", tags=["Al Jazeera English"])
add("http://www.guardian.co.uk/rssfeed/0,,1,00.xml", tags=["Network Front"])
add("http://www.democracynow.org/democracynow.rss", tags=["Democracy Now!"])
add("https://firstlook.org/theintercept/feed/", tags=["The Intercept"])
add("http://www.scmp.com/rss/91/feed", tags=["South China Morning Post"])
add("http://rt.com/rss/", tags=["RT - Daily news"])
add("http://www.xinhuanet.com/english/rss/chinarss.xml", tags=["XINHUANEWS"])
add("http://syndication.apn.co.nz/rss/uttm.xml", tags=["New Zealand Herald"])
add("http://news.google.com/news?hl=en&gl=us&q=irish%20times&um=1&ie=UTF-8&output=rss", tags=["irish times - Google News"])
add("http://timesofindia.indiatimes.com/rssfeedsdefault.cms", tags=["The Times of India"])
add("http://www.nation.co.ke/-/1148/1148/-/view/asFeed/-/vtvnjq/-/index.xml", tags=["Daily Nation RSS Feeds"])
add("http://www.lemonde.fr/rss/sequence/0,2-3208,1-0,0.xml", tags=["Le Monde.fr"])
add("http://www.straitstimes.com/news/singapore/rss.xml", tags=["RSS Breaking News"])
add("http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml", tags=["NYT > Home Page"])
add("http://www.elmercuriomediacenter.cl/feed/", tags=["El Mercurio Media Center"])
add("http://www.nacion.com/Generales/RSS/EdicionRss.aspx?section=portada", tags=["La Nación - Home"])
add("http://www.elpais.com/rss/feed.html?feedId=1022", tags=["Portada de EL PAÍS"])
add("http://www.nstp.com.my/feed/", tags=["The New Straits Times Press (Malaysia) Berhad"])
add("http://feeds.feedburner.com/EverydayFeminism", tags=["Everyday Feminism"])
add("http://feeds.feedburner.com/Autostraddle", tags=["Autostraddle"])
add("http://blackgirldangerous.tumblr.com/rss", tags=["Black Girl Dangerous"])
add("http://www.feministfrequency.com/feed/", tags=["Feminist Frequency"])
add("http://afroculinaria.com/feed/", tags=["Afroculinaria"])
add("http://kartoza.com/feed/", tags=["Kartoza"])
add("http://pvanb.wordpress.com/feed/", tags=["Ecostudies"])
add("http://rammb.cira.colostate.edu/projects/npp/blog/index.php/feed/", tags=["Suomi NPP (National Polar"])
add("http://mapperz.blogspot.com/feeds/posts/default", tags=["Mapperz - The Mapping News Blog"])
add("http://mapbox.com/blog/blog.rss", tags=["Blog - Mapbox"])
add("http://planet.qgis.org/planet/feed/rss/", tags=["QGIS Planet"])
add("http://hot.openstreetmap.org/feed", tags=["Humanitarian OpenStreetMap Team"])
add("http://www.opengeodata.org/?feed=rss2", tags=["OpenStreetMap Blog"])
add("http://www.spatiallyadjusted.com/feed/", tags=["Spatially Adjusted"])
add("http://nathanw.net/feed.xml", tags=["Nathan Woodrow"])
add("http://www.blogger.com/feeds/1631047127449001675/posts/default", tags=["Letters from the SAL"])
add("http://www.carsonfarmer.com/feeds/all.atom.xml", tags=["Carson Farmer"])
add("http://bigthink.com/blogs/strange-maps.rss", tags=["Strange Maps"])
add("http://radicalcartography.blogspot.com/feeds/posts/default", tags=["radicalcartography"])
add("http://feeds.feedburner.com/verysmartbrothas", tags=["VSB"])
add("http://blavity.com/feed/", tags=["Blavity"])
add("http://racialicious.tumblr.com/rss", tags=["Racialicious"])
add("http://www.rsspect.com/rss/vagrant.xml", tags=["Hark, A Vagrant!"])
add("http://postsecret.blogspot.com/feeds/posts/default", tags=["PostSecret"])
add("http://what-if.xkcd.com/feed.atom", tags=["What If?"])
add("http://xkcd.com/rss.xml", tags=["xkcd.com"])
add("http://www.smbc-comics.com/rss.php", tags=["Saturday Morning Breakfast Cereal"])
add("http://feeds.feedburner.com/flavorwire-rss", tags=["Flavorwire"])
add("http://okfnlabs.org/blog/feed.xml", tags=["Open Knowledge Foundation Labs"])
add("http://blog.sunlightfoundation.com/feed/", tags=["Sunlight Foundation Blog"])
add("http://devinit.org/feed/", tags=["Development Initiatives"])
add("http://www.aidinfolabs.org/feed", tags=["aidinfo labsaidinfo labs"])
add("https://iati.github.io/feed.xml", tags=["IATI Code Blog"])
add("http://feeds.feedburner.com/breitbart", tags=["Breitbart"])
add("http://www.weeklystandard.com/weblogs/TWSFP/atom.xml", tags=["The Weekly Standard Blog"])
add("http://www.nationalreview.com/author/897/feed", tags=["National Review Online"])
add("http://feeds.feedburner.com/thepointsguy", tags=["The Points Guy"])
add("http://feeds.gawker.com/lifehacker/vip", tags=["Lifehacker"])
